package runtime

import (
	"os"
	"path/filepath"
	"strings"
)

// productionEnvName is the dotenv file Vite, Next.js, and CRA load
// during a production build. Forge writes it into the confined build
// directory so `import.meta.env.VITE_*` / `process.env.NEXT_PUBLIC_*`
// are inlined at compile time. Passing the same keys only at
// `docker run` is too late: the JS bundle already contains empty
// strings, which is why EmailJS reported "public key is required".
const productionEnvName = ".env.production.local"

// writeProductionEnv materializes operator env for the image build.
//
// Empty env leaves any repository file alone. Non-empty env overwrites
// so dashboard values win over committed defaults. Values are never
// returned — callers must not append this file to build_log.
func writeProductionEnv(dir string, env []EnvPair) error {
	if len(env) == 0 {
		return nil
	}
	body, err := formatProductionEnv(env)
	if err != nil {
		return err
	}
	if err := writeExtraFiles(dir, map[string]string{productionEnvName: body}); err != nil {
		return err
	}
	return os.Chmod(filepath.Join(dir, productionEnvName), 0o600)
}

func formatProductionEnv(env []EnvPair) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by Forge for this deploy. Not operator source.\n")
	for _, ev := range env {
		if err := validateEnvPair(ev); err != nil {
			return "", err
		}
		b.WriteString(ev.Key)
		b.WriteByte('=')
		b.WriteString(quoteDotEnv(ev.Value))
		b.WriteByte('\n')
	}
	return b.String(), nil
}

func quoteDotEnv(v string) string {
	if v == "" {
		return ""
	}
	if !strings.ContainsAny(v, " \t\"'#\\$") {
		return v
	}
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range v {
		switch r {
		case '\\', '"':
			b.WriteByte('\\')
		}
		b.WriteRune(r)
	}
	b.WriteByte('"')
	return b.String()
}
